// Generated by CoffeeScript 1.7.1
(function() {
    var Person, person1, person2;

    Person = (function() {
        function Person(name) {
            this.name = name;
        }

        Person.prototype.sayHello = function() {
            return console.log("hello, i'm", this.name);
        };

        return Person;

    })();

    person1 = new Person("manu ginobili");

    person2 = new Person("jeremy lin");

    console.log("person1", person1);

    console.log("person2", person2);

    person1.sayHello();

    person2.sayHello();

}).call(this);