// Generated by LiveScript 1.2.0
(function() {
    var Runnable, Renamable, A, a;
    Runnable = {
        run: function() {
            return "run!!";
        }
    };
    Renamable = {
        setName: function(name) {
            this.name = name;
        },
        getName: function() {
            var ref$;
            return (ref$ = this.name) != null ? ref$ : this.id;
        }
    };
    A = (function() {
        A.displayName = 'A';
        var prototype = A.prototype,
            constructor = A;
        importAll$(prototype, arguments[0]);
        importAll$(prototype, arguments[1]);

        function A() {
            this.id = Math.random() * 1000;
        }
        return A;
    }(Runnable, Renamable));
    a = new A;
    a.setName("Achi");
    console.log("a.get-name!", a.getName());
    console.log(a.run());

    function importAll$(obj, src) {
        for (var key in src) obj[key] = src[key];
        return obj;
    }
}).call(this);